version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
    # You can also specify other tool versions:
    # nodejs: "16"
  commands:
    - pip install mkdocs-material
    - mkdocs build --site-dir $READTHEDOCS_OUTPUT/html